# Generated by Django 3.2.9 on 2021-12-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, choices=[('KNUST', 'Knust'), ('UG', 'UG')], max_length=5),
        ),
    ]
