# Generated by Django 3.2.9 on 2021-12-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_address'),
    ]

    operations = [
    ]
