# Generated by Django 3.2.9 on 2021-11-18 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='customer',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
    ]
