# Generated by Django 3.2.9 on 2021-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20211118_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='terms',
            new_name='agreed_to_terms',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
