# Generated by Django 3.2.9 on 2021-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_authtoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agreed_to_terms',
            field=models.BooleanField(),
        ),
    ]
