# Generated by Django 3.2.9 on 2021-12-05 17:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_agreed_to_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='id_char',
        ),
        migrations.AddField(
            model_name='merchant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_card',
            field=models.ImageField(null=True, upload_to='merchant/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_card_type',
            field=models.CharField(choices=[('national', 'National'), ('driver', 'Driver'), ('student', 'Student'), ('voter', 'Voter')], default='Student', max_length=8),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
