# Generated by Django 3.2.9 on 2021-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20211205_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
