# Generated by Django 3.2.9 on 2021-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
