# Generated by Django 3.2.9 on 2021-12-29 22:53

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, default='default/defaultvid.mp4', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='products/video/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
