# Generated by Django 3.2.9 on 2021-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productanswer',
            name='status',
        ),
        migrations.AddField(
            model_name='productanswer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
