# Generated by Django 3.2.9 on 2021-11-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211122_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productanswer',
            old_name='is_active',
            new_name='active',
        ),
    ]
