# Generated by Django 3.2.9 on 2021-12-31 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_product_long_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="in_stock",
            new_name="stock",
        ),
    ]
