# Generated by Django 3.2.9 on 2022-01-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_in_stock_product_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmedia",
            options={
                "ordering": ("created",),
                "verbose_name": "Product Media",
                "verbose_name_plural": "Product Media",
            },
        ),
        migrations.RenameField(
            model_name="productmedia",
            old_name="raw_image",
            new_name="image",
        ),
    ]
