# Generated by Django 3.2.9 on 2021-12-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211215_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ('-created',), 'verbose_name': 'Product Media', 'verbose_name_plural': 'Product Media'},
        ),
    ]
