# Generated by Django 3.2.9 on 2022-02-26 00:20

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    operations = [TrigramExtension()]
