name: Pytest CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ceillo@123
          POSTGRES_USER: ceillo

    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: apt-get install -y libpq-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
      - name: Run Tests
        run: |
          pytest
          